services:
  postgres:
    image: postgres:14.5-alpine
    container_name: hw-1.0
    ports:
      - "56721:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - hw-1:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - 'MINIO_ROOT_USER=user'
      - 'MINIO_ROOT_PASSWORD=password'
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - 'MONGO_INITDB_DATABASE=homework'
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --logLevel warning --requirepass password
volumes:
  hw-1: