server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/dz1'
    username: 'postgres'
    password: '123'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db-changelog.xml
  graphql:
    graphiql:
      enabled: true
    path: /graphql
