server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: '123'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db-changelog.xml
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: homework
    redis:
      host: localhost
      port: 6379
      password: password
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 30000

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760
